# Generated by Django 4.1.3 on 2022-12-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Math', 'Math'), ('Pyhsics', 'Pyhsics'), ('Algebra', 'Algebra'), ('English', 'English')], max_length=20, null=True)),
            ],
        ),
    ]
